blueprint:
  name: "AmpliPi Announce"
  description: "Easy to use announcement builder"
  domain: automation
  author: Micro-Nova

  input:
    trigger_input:
      name: "Triggers"
      description: "What would you like to cause the automation to execute?"
      selector:
        trigger:

    zones:
      name: "Zones"
      description: "Select one or more zones/groups for audio output"
      selector:
        entity:
          filter:
            - device_class: speaker
            - integration: AmpliPi
          multiple: true

    message:
      name: "Message"
      description: "What would you like to announce?"
      selector:
        text:
          multiline: true

    volume:
      name: "Volume"
      description: "Select what volume to start the zones on"
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          mode: slider

    cache:
      name: "Cache"
      description: "Would you like to save the tts to the disk? Good if you expect to use this announcement often, bad if this is a one-off or uncommon announcement."
      default: true
      selector:
        boolean:
        
mode: single

trigger: !input trigger_input

action:
  - service: media_player.volume_set
    data:
      volume_level: !input volume
    target:
      entity_id: media_player.amplipi_announcement

  - repeat:
      for_each: !input zones
      sequence:
        - service: media_player.select_source
          target:
            entity_id: media_player.amplipi_announcement
          data:
            source: "{{ repeat.item }}"

  - service: tts.speak
    data:
      cache: !input cache
      media_player_entity_id: media_player.amplipi_announcement
      message: !input message
    target:
      entity_id: tts.google_translate_en_com
      